screwdriver-cd/store

plugins/builds.js

This is because when passed as environment variables, they are assumed to be strings.

Force integer conversion for config settings

---

config/custom-environment-variables.yaml

catbox-s3 now supports a custom endpoint for S3. fhemberger/catbox-s3#53
This PR adds `endpoint` config to use S3 compatible storages.

Add endpoint config for s3

---

bin/server
config/custom-environment-variables.yaml
config/default.yaml
lib/server.js
test/lib/server.test.js

Enable cors for UI, so that UI can get the artifact manifest.
Related to https://github.com/screwdriver-cd/screwdriver/issues/468

feat(468): enable cors for ui

---

.eslintignore
bin/server
config/custom-environment-variables.yaml
vendor/catbox-s3/LICENSE.txt
vendor/catbox-s3/README.md
vendor/catbox-s3/index.js
vendor/catbox-s3/lib/index.js
vendor/catbox-s3/package-lock.json
vendor/catbox-s3/package.json
vendor/catbox-s3/test/.eslintrc
vendor/catbox-s3/test/index.js

The store is unable to interact with objects stored in an encrypted S3 bucket. This is due to a rejection from AWS for not providing the *Signature Version* along with our S3 requests.
We use `catbox-s3` to abstract the S3 interactions, which currently does not allow the user to specify the `signatureVersion` client option. By choosing to vendor a fix, we can deploy the patched version without being blocked on the upstream dependency to take in the update.
Vendor in a patched `catbox-s3` module that will allow us to specify the *Signature Version* when interacting with an encrypted S3 bucket.
* PR for upstream fix: https://github.com/fhemberger/catbox-s3/pull/55

fix: Vendor updated `catbox-s3` module

---

screwdriver.yaml

The *Store* pipeline is broken due to a failure during `semantic-release` step
Use the `screwdriver-cd/semantic-release` template.

chore: publish using semantic-release template

---

package.json
plugins/auth.js
test/plugins/auth.test.js

We would like to increase security on store endpoints. Currently, anyone can make requests to the store without a token for build artifacts. By requiring the store to take in a token, only requests made with a JWT will work against the store for artifacts. We need to allow tokens to be passed through the URL so the UI can make calls to the Store using the user's token when the user clicks on artifact links in the UI.
This PR switches from using `hapi-auth-jwt` to `hapi-auth-jwt2`.
- Similar PR: https://github.com/screwdriver-cd/screwdriver/pull/738
- NPM package: https://www.npmjs.com/package/hapi-auth-jwt2

fix: Allow tokens to be passed into the URL

---

config/custom-environment-variables.yaml
config/default.yaml
vendor/catbox-s3/lib/index.js

S3 storage strategy (catbox-s3) supports **virtual-hosted-style** URL by default and does not provide a flag to use **path-style** URL.
- virtual-hosted-style: http://bucket.s3.example.com
- path-style: http://s3.example.com/bucket
This PR adds path-style URL switch flag and makes it possible for users to use a S3 compatible server (that supports path-style only, e.g. Minio) easily.
- [s3ForcePathStyle-property](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#s3ForcePathStyle-property)

fix: add path-style URL switch flag for S3 strategy.

---

package.json

Updating hoek and joi packages to address Snyk vulnerabilities
**Notes**:
- currently not possible to update to hapiv17 since there are no versions of `hapi-jwt-auth2` that support hapiv17.
- cannot update [good](https://www.npmjs.com/package/good) since good 8 only supports hapi 17+.
- boom 6.0.0+ seems to only support node8
- [hapi-swagger](https://www.npmjs.com/package/hapi-swagger) must use versions v7.x.x of this module for hapi <17.
- inert 5.0.0 only supports hapi > 17. (https://github.com/hapijs/inert/commit/dfcd06685a8c095655625aeb17f10431c1919058)
- vision 5.0.0 also only supports hapi > 17. https://github.com/hapijs/vision/commit/59775f70ab0e80a12da3618681883b2ddca6f8ac
Related to https://github.com/screwdriver-cd/store/pull/31

fix: Update hoek and joi packages to latest

---

package.json

Grab the latest copy of the catbox-s3 plugin as it now supports [IAM roles in EC2](https://github.com/fhemberger/catbox-s3/pull/59)

feat: Pull in S3 IAM fix

---

screwdriver.yaml

Don't need those scripts anymore since we're using semantic release
https://github.com/screwdriver-cd/toolbox/blob/master/docker-trigger.sh
https://gist.github.com/stjohnjohnson/3d2388b2a7ba658cdcdaffa8cd874e50#file-docker-sh

fix: Remove extra git scripts from publish job

---

screwdriver.yaml

git tag's sorting order is alphabetical not based on the time. git describe --tags will give the latest tag instead

fix: get latest tag

---

package.json

Builds are currently failing due to a version mismatch with Joi; the `package-lock.json` file in the data-schema is set to `13.1.2`.
* Fix issues related to `screwdriver-data-schema` by pinning Joi version

fix: Pin Joi version to 13.1.2

---

plugins/commands.js
test/plugins/commands.test.js

We need an endpoint to be able to delete command binaries from the store.
API PR to delete commands: https://github.com/screwdriver-cd/screwdriver/pull/990
UI PR to delete commands: https://github.com/screwdriver-cd/ui/pull/281

feat: Delete commands endpoint

---

plugins/builds.js
screwdriver.yaml
test/plugins/builds.test.js

We are seeing failure when pushing large artifact to store. Issue: https://github.com/screwdriver-cd/screwdriver/issues/1072
This PR will fix the issue by:
1. For `content-type: text:plain`: save only request.payload(Buffer) to cache
2. For other types:  still preserve headers and wrap header and payload inside object
e.g. we're using `content-type: application/x-ndjson` for uploading logs
Tested locally with in-a-box: both `catbox-memory` and `catbox-s3` work fine and can upload big file now.

fix: do not wrap artifact inside object

---

lib/server.js

Increase request timeout to 60s from 10s cuz it can take a long time when uploading to S3 sometimes.
This giving 408 in the build!

fix: increase request timeout to 60s

---

screwdriver.yaml

sleep 10 before checking the endpoint since it took sometime for the pod to be ready
Always need to rerun jobs to make it pass now: https://cd.screwdriver.cd/pipelines/24/events

fix: sleep 10 before checking the endpoint

---

screwdriver.yaml

Our builds keep failing because 10 secs wait is not enough, the service is not back up.

fix: increase wait time to 15 sec after deployment

---

plugins/caches.js
test/plugins/caches.test.js

Missing `/caches/` in front
Related: https://github.com/screwdriver-cd/screwdriver/issues/1281, https://github.com/screwdriver-cd/screwdriver/issues/1257

fix: fix endpoint

---

helpers/aws.js
plugins/caches.js
test/helpers/aws.test.js
test/plugins/caches.test.js

We will no longer compute the md5 of the zip, since zip always changes because of the `last modified` metadata in the zip file. 
Instead, we will upload a md5json file contains all md5 of files in the folder. Then we will perform the comparison in the `store-cli` to figure out whether it is necessary to upload. 
Related:
https://github.com/screwdriver-cd/store-cli/pull/11
https://github.com/screwdriver-cd/screwdriver/issues/1257
https://github.com/screwdriver-cd/screwdriver/issues/1281

fix(1257): remove checksum, add tests

---

config/default.yaml

For public accessible or role based permission model, S3 buckets do not need IAM user. Set the default value to null to avoid always passing in access key.

fix: set accesskey default value to null

---

config/custom-environment-variables.yaml
config/default.yaml
package.json

Store artifacts, logs, caches to disk: https://github.com/mirusresearch/catbox-disk.
So that in the chart, we can configure to use this option to avoid external dependencies, e.g.s3, while still keeping the persistency of data. (can make the cache dir a persistent volume in k8s)

fix: add catbox-disk

---

plugins/builds.js

For text/plain payload or application/zip, upload it as Buffer
Otherwise, catbox-s3 will try to JSON.stringify (https://github.com/fhemberger/catbox-s3/blob/master/lib/index.js#L236) and might create issue on large payload
Related: https://github.com/screwdriver-cd/screwdriver/issues/1257, https://github.com/screwdriver-cd/screwdriver/issues/1281

fix: upload large payload for cache

---

plugins/caches.js
test/plugins/caches.test.js

Adding support for job and pipeline level caches.
Related: https://github.com/screwdriver-cd/screwdriver/issues/1280
https://github.com/screwdriver-cd/screwdriver/issues/1257

fix: Extend caching scope to jobs and pipelines

---

config/custom-environment-variables.yaml
config/default.yaml
helpers/aws.js
package.json
plugins/caches.js
test/helpers/aws.test.js
test/plugins/caches.test.js

Currently there's no mechanism to be able to destroy a cache other than using store-cli on a job. This PR is part of the feature to invalidate cache through a button in the UI (individually for pipeline and job caches).

fix: Endpoint to invalidate cache

---

plugins/caches.js
test/plugins/caches.test.js

Allow PR jobs to get its parent job. For example: `PR-1:main` can get cache from `main`
Blocked by: https://github.com/screwdriver-cd/screwdriver/pull/1409
Related: https://github.com/screwdriver-cd/screwdriver/issues/1382

fix: allow pr job to get its parent cache

---

helpers/aws.js
package.json
plugins/caches.js
plugins/commands.js
test/plugins/caches.test.js
test/plugins/commands.test.js

The helper client only points to AWS.
This PR enables to use cache invalidation in S3 compatible.
And add more logs for debugging.

fix: enable to use s3 compatible

---

plugins/builds.js
test/plugins/builds.test.js

make artifact downloaded by the browser
Browser can sniff the mime type from the file signature, and that's why your browser decides to display file on web page sometimes while, instead, download it, the other times.
related to: https://github.com/screwdriver-cd/screwdriver/issues/1476
related PRs:
- https://github.com/screwdriver-cd/screwdriver/pull/1498
- https://github.com/screwdriver-cd/ui/pull/408

fix: artifact is to be downloaded

---

helpers/aws.js
plugins/caches.js
screwdriver.yaml
test/helpers/aws.test.js
test/plugins/caches.test.js

- Currently, hapi stores payload in raw Buffer,  which is taking a lot of memory when uploading big files. Store pods are getting killed by OOM.
- This PR will stream download and upload for all the `zip` files for `caches` endpoint if using `s3`. Other cases will not be changed. It will still do upload / download as the old way.
- `maxBytes` won't work as what it was before since the data is a stream. But we still need it since the default value is `1m`. If the part of stream reading in is larger than that, hapi will throw 413.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1561

fix: stream caches download and upload for s3

---

helpers/aws.js

This is dumping a lot noise to the logs and increase unnecessary memory usage

fix: remove the logging for chunk data length

---

plugins/builds.js

**Description of changes:**
When we cannot use `SD_ZIP_ARTIFACTS` options because of not using AWS Lambda, other type than `.zip` file can also become large size.
Even if that case, we want to use stream upload because that file can also become large size.
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.

feat: Always using stream upload when using s3 storage

---

config/custom-environment-variables.yaml
config/default.yaml
helpers/aws.js
test/helpers/aws.test.js

We want to customize aws-sdk's partSize option for upload method.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property
Add partSize option to config, and pass partSize option to upload method.

feat: Enable to change partSize option

---

README.md
package.json

The instruction in the current README only has strategy for in memory, this PR adds instruction to use `catbox-disk` strategy to persist data in disk.
Add instruction to how to use `disk` strategy to REAMDE

fix(readme): update README with catbox-disk strategy

---

README.md
config/custom-environment-variables.yaml
config/default.yaml
lib/server.js
test/lib/server.test.js

Config multiple cors endpoint in store is not possible. One can only set cors to be one endpoint.
Before, in `config/` you can only specify 
```
ecosystem:
allowCors: 'http://localhost:4200'
```
After this PR, you could make `allowCors` to be an array
```
ecosystem:
allowCors: ['http://localhost:4200', 'http://localhost:4201']
```

[Feature] Allow to config cors to be an array of strings instead of one string

---

plugins/builds.js
test/plugins/builds.test.js

**Issue #, if available:**
**Description of changes:**
html artifacts (like diff-cover output) is displayed in browser as plain text. This change will set the proper content-type for html artifacts so they are displayable.
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.

have proper content-type for html files

---

plugins/builds.js
test/plugins/builds.test.js

Content-Disposition header can not accept Japanese as the filename.
```
190725/035746.918, (1564027066918:prod-sdstore-7995d6889c-skz6z:878:jyi5b9tc:10015) [error] message: The header content contains invalid characters, stack: TypeError: The header content c
ontains invalid characters
at validateHeader (_http_outgoing.js:494:11)
at ServerResponse.setHeader (_http_outgoing.js:498:3)
at Object.internals.writeHead (/usr/src/app/node_modules/hapi/lib/transmit.js:323:21)
at Object.internals.transmit (/usr/src/app/node_modules/hapi/lib/transmit.js:105:15)
at Object.exports.send (/usr/src/app/node_modules/hapi/lib/transmit.js:32:25)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```
Adding encoding to the filename, the artifact is able to be download.
This …

fix: Failed to download artifacts that have Japanese filename

---

helpers/iframe.js

For artifacts preview, the href link in the html are prefixed with API bluntly. This PR will only mask href links that are `relative path`, i.e.  `/plugins/x/y.html`
If these links are
1) absolute path like `https://istanbul.js.org/`, 
2) relative path acting like anchor tag, i.e  `#L3` or `#summary`
We will skip masking.
Skip api prefix masking for `absolute path` or `#anchor`
https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

feat: add absolute path check and skip API prefix if its absolute path

---

helpers/iframe.js
helpers/mime.js
plugins/builds.js

People want to see their css and js files loaded in the artifacts preview, we heard you and we are making it happening. ❤️ ❤️ 
This PR adds artifacts preview with css and js loaded inside the iframe.
Before:
After:

feat: artifacts made iframe script to mask css and js relative links

---

helpers/iframe.js

Image urls that are relative path would be rendered as expected. We need to prefix api endpoint to images that have relative paths.
Add api prefix to image links

feat: replace relative image links to be prefixed with api endpoint

---

helpers/mime.js
plugins/builds.js

Firefox:
Firefox is not displaying images from artifacts.
Chrome:
The root case is that `IE` and `Chrome` are doing some MIME sniffing by default, while Firefox doesn’t. Ironically, Firefox is the one upholds the principle in the W3C guide, again.
This PR adds `png`, `jpg` and `jpeg` extensions to images to set MIME type explicitly.  
Live Demo: https://cd.screwdriver.cd/pipelines/3687/events
Corresponding Screwdriver Repo: https://github.com/screwdriver-cd-test/artifacts-test
- [Properly Configuring Server MIME Types - Web security](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types)
- [How Mozilla determines MIME Types - Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/How_Mozilla_determines_MIME_Types)
- [Media Types by …

fix: artifacts images not displayed correctly in Firefox

---

helpers/mime.js
package.json

Instead of maintaining the MIME types in the `helpers/mime.js`, we can take advantage and offload the MIME lookup to [mime-types](https://www.npmjs.com/package/mime-types) instead.
This PR removes the homebrew mime helpers, and utilize [mime-types (https://github.com/jshttp/mime-types) as suggested in [pullrequestreview-327807721](https://github.com/screwdriver-cd/store/pull/95#pullrequestreview-327807721)
Thank you @DekusDenial for point out. I used [file-type](https://www.npmjs.com/package/file-type) and does way too much than we need here. `mime-types` seems to fit the needs, so refactoring code accordingly. 
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to …

fix: incorporated mime-types library

---

.gitignore
config/custom-environment-variables.yaml
config/default.yaml

Currently the screwdriver store uses catbox-s3 which by default will attempt to establish the s3 cache using public-read ACL. This is a no go for private repos, and private clusters as far as my company is concerned. 
Allow the ACL setting to be passed through to catbox-s3, such that a screwdriver cluster manager can override the ACL from public-read to private. 
https://github.com/screwdriver-cd/screwdriver/issues/1934

fix: private s3 bucket, config to take ACL param

---

Dockerfile
package.json
screwdriver.yaml
test/lib/server.test.js

Screwdriver API is running on node:8 container which is no longer supported.
Upgrade to latest LTS of node. 
https://github.com/screwdriver-cd/screwdriver/issues/1722
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

fix(1957): move to node:12

---

package.json
plugins/caches.js
test/plugins/caches.test.js

Clear Cache api in store reaches out to SD API to check for admin permissions of user. As this can be achieved in SD API, this api call is no longer required.
This PR removes the check for user admin permissions and relies on SD api to verify it.
https://github.com/screwdriver-cd/screwdriver/issues/2087

feat(2087): Defer check for admin to API and add auth scope sdapi

---

config/custom-environment-variables.yaml
config/default.yaml
helpers/aws.js
package.json

Default timeout of 2mins doesn't match with configured timeout from log-service which is 20s
Allow cluster admin to configure max s3 http timeout.
https://github.com/screwdriver-cd/log-service/blob/master/sduploader/sdstoreuploader.go#L37

fix: control max http timeut

---

bin/server
helpers/aws.js
lib/server.js
package.json
plugins/builds.js
plugins/caches.js
plugins/commands.js
plugins/logging.js
test/lib/server.test.js
test/plugins/auth.test.js
test/plugins/builds.test.js
test/plugins/caches.test.js
test/plugins/commands.test.js
test/plugins/logging.test.js
test/plugins/stats.test.js
test/plugins/status.test.js
test/plugins/swagger.test.js

Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR majorly upgrades @hapi/hapi version and other changes to be compatible with latest @hapi js dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/1958

feat(1958): Upgrade to @hapi/hapi v19.x.x. BREAKING CHANGE: new major data-schema

---

config/default.yaml

s3 object ACL should be private by default, meaning only the owner has the full control
this PR fixes the default value of ACL which got passed to catbox-s3 plugin
https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

fix: s3 object ACL should be private by default

---

helpers/aws.js
plugins/commands.js
test/helpers/aws.test.js
test/plugins/commands.test.js

Shared commands expire due to a side effect of using catbox-s3
Avoid using catbox-s3 for commands
https://github.com/screwdriver-cd/screwdriver/issues/2058

fix(2058): shared command expiry

---

plugins/builds.js
test/helpers/aws.test.js

When downloading files above 1G Store is going OOM
When downloading files from Store output should be streamed.

fix: always use aws cli for s3.

---

bin/server
config/default.yaml
helpers/aws.js
helpers/mime.js
plugins/auth.js
plugins/builds.js
test/plugins/builds.test.js

1. increase token timeout to 13hrs
2. map yidf/state to txt extension
3. make sure html files can be rendered when using s3

fix(): when using s3, parse stream output to buffer for html files

---

helpers/mime.js

Chrome is not displaying xml file with error "Resource interpreted as Document but transferred with MIME type application/xml"

fix: force xml as text so that it's displayed in Chrome

---

helpers/mime.js

~To display yaml as text file, so we need to return type as `text/yaml` instead~
Add `add text/yaml to know MIME types
Instead of `application/octet-stream` during preview mode for `yaml` files, we want to return the type as `text/yaml`, so that it can be displayed in UI's artifacts preview window
Because `application/*` will be treated as binary, thus trigger downloads

fix: add yaml to MIME types

---

helpers/mime.js
lib/server.js
plugins/builds.js
test/plugins/builds.test.js
test/plugins/data/helloworld.html

Follow up for [PR 120](https://github.com/screwdriver-cd/store/pull/120) 
Testing Repo: https://github.com/adong/artifacts-test/tree/master
<details>
<summary></summary>
I think its normal to show content-length 0 for redirects [302](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302)
The redirected link shows correct `content-length`
</details>
=> It turns out to be `store/node_modules/@hapi/hapi/lib/response.js` 
```js
get contentType() {
let type = this.headers['content-type'];
if (type) {
type = type.trim();
if (this.settings.charset &&
type.match(/^(?:text\/)|(?:application\/(?:json)|(?:javascript))/) &&
!type.match(/; *charset=/)) {
const semi = type[type.length - 1] === ';';
return type + (semi ? ' ' : '; ') + 'charset=' + this.settings.charset;
}
return type;
}
if …
```

fix: update MIME types

---

helpers/aws.js
plugins/builds.js
plugins/caches.js
test/helpers/aws.test.js
test/plugins/builds.test.js
test/plugins/caches.test.js

API is not returning Content-Length header when using s3. This causes large file downloads to wait indefinitely without any visuals on when it will complete. 

fix: return content length for artifacts when using S3

---

package.json

Request package is deprecated.
This PR removes the unused request package from the package.json.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1961

fix(1961): Remove request package

---

plugins/builds.js
test/plugins/builds.test.js

Allow `unzip_worker` scope token for `GET /v1/builds/{id}/{artifacts*}` and `PUT /v1/builds/{id}/{artifacts*}`.
- Allow `unzip_worker` scope in builds plugin
- Add test cases to verify that `unzip_worker` scope token can be used
https://github.com/screwdriver-cd/screwdriver/issues/1500
https://github.com/screwdriver-cd/screwdriver/pull/2583
https://github.com/screwdriver-cd/queue-service/pull/37

fix(1500): Enable to Upload and Download artifact files by unzip worker scope token

---

bin/server

when using memory strategy, it throws `TypeError: strategy is not a constructor` because of `@hapi/catbox-memory` dependency update
fix syntax error

fix: fix strategy map on server start

---

helpers/aws.js
plugins/commands.js
test/helpers/aws.test.js
test/plugins/commands.test.js

This PR will use Stream when uploading commands from store to Object Storage.
It is better to use Stream as well as Build log.
This is useful for uploading large commands.
The following PRs started using Stream processing. However, it has been reverted back to using Buffer.
https://github.com/screwdriver-cd/store/pull/111
Probably the previous fix caused an error when downloading the command.
The reason is that there was missing metadata in the upload.
If the metadata is missing, the json parse will fail at the following code.
https://github.com/screwdriver-cd/store/blob/f3ee5e810a95a4c0484948988b3a60f6388e8722/helpers/aws.js#L264
This PR creates a new function.
The existing "uploadAsStream" function cannot be used in the command upload because it depends on multi-part-upload in the …

fix: Command upload to process using stream

---

helpers/mime.js
plugins/builds.js
test/plugins/builds.test.js

Related to issue https://github.com/screwdriver-cd/screwdriver/issues/2889,
For PR https://github.com/screwdriver-cd/screwdriver/pull/2888, after relaxing the backend, we run into an issue that 
```
module script but the server responded with a MIME type of "text/plain". 
Strict MIME type checking is enforced for module scripts per HTML spec.
```
This PR adds more support besides, `download`, `preview` and raw mime type from the library itself.
https://github.com/screwdriver-cd/screwdriver/issues/2889

fix(2889): allow to get mime type directly by adding raw flag

---

helpers/mime.js
plugins/builds.js
test/plugins/builds.test.js

1) revert https://github.com/screwdriver-cd/store/pull/140, since it's not needed
2) allow `.js` to be loaded and handle that render/download to the browser
Made loading storybook available, see screenshot:
Before: 
After:
https://github.com/screwdriver-cd/screwdriver/issues/2889

fix(2889): remove raw feature and allow artifacts renders SPA

---

Dockerfile
plugins/shutdown.js
test/plugins/shutdown.test.js

Store server cannot receive `SIGTERM`, and moreover the store even does not have the method of shutdown like api.
See this issue for details:
https://github.com/screwdriver-cd/screwdriver/issues/3062
- Fix Dockerfile as belows:
- Add tini process
- Run the service by `node ./bin/server` directly, not via `npm start`
- Add shutdown method
Issue: https://github.com/screwdriver-cd/screwdriver/issues/3062
Docker and Node.js Best Practices: 
https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals

fix(3062): fix Dockerfile not to use `npm start`, and add shutdown method

---

config/custom-environment-variables.yaml
config/default.yaml
plugins/auth.js
test/lib/server.test.js
test/plugins/auth.test.js

The jwt expiration is currently 13h and is written directly in the source code.
This makes it difficult for SD administrators to change to arbitrary values to suit their use cases.
Can be configured from config file or environment variable.
https://github.com/screwdriver-cd/guide/pull/600

feat: Replace jwt expiration with a config and environment variable

---

plugins/caches.js
test/plugins/caches.test.js

I would like to reduce unnecessary retries when uploading large files.
By using the `Expect: 100-continue` header, the content length can be checked before the body is uploaded.
Thus, the HTTP client (store-cli) can receive a 413 error earlier without unnecessary retries.
I have also submitted a related PR to `store-cli`.
https://github.com/screwdriver-cd/store-cli/pull/82
To reduce unnecessary retries, return a 413 error earlier.
[issue](https://github.com/screwdriver-cd/screwdriver/issues/3013)
[store-cli](https://github.com/screwdriver-cd/store-cli/pull/82)

feat(3013): Add handling for the Expect header at onPreAuth
