index.js, lib/server.js, package.json, plugins/stats.js, test/lib/server.test.js, test/plugins/auth.test.js, test/plugins/builds.test.js, test/plugins/logging.test.js, test/plugins/stats.test.js, test/plugins/status.test.js, test/plugins/swagger.test.js
=> fix eslint

screwdriver.yaml
- Added K8S_TOKEN secret to Store pipeline
- Added beta deploy step only so far, will add prod deploy later
=> Add beta deploy step to yaml

README.md, screwdriver.yaml
- Add prod deploy step using semantic release
- Also update Screwdriver pipeline badge link in README
=> feat: Add prod deploy step to yaml

screwdriver.yaml
Forgot to add docker repo to publish step
Related to #17 #16
=> fix: Add docker repo to publish step in yaml

plugins/builds.js, test/plugins/builds.test.js
Enable read protection for store
Make /GET calls to store require JWT authentication
=>  fix(858): Enable auth for artifact reads

screwdriver.yaml
Should be hitting the status endpoint, otherwise we get a 404
=> fix: Update curl endpoint

plugins/caches.js, test/plugins/caches.test.js
Related PR: https://github.com/screwdriver-cd/store/pull/49
=> fix: Implement cache DELETE endpoint

helpers/aws.js, plugins/caches.js, screwdriver.yaml
Tested locally and found a few issues:
Related: screwdriver-cd/screwdriver#1281, screwdriver-cd/screwdriver#1257
=> fix: Set proper cacheKey and StorageClass

plugins/builds.js, test/plugins/builds.test.js
decide to use the org filename anyway
=> fix: honor artifact filename

helpers/helper.js, plugins/builds.js, plugins/caches.js, test/plugins/builds.test.js, test/plugins/caches.test.js
- streaming all .zip artifacts since that can be huge
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1589
=> fix: stream artifact zip

plugins/builds.js, test/plugins/builds.test.js
=> fix: fix param name

bin/server, helpers/aws.js, package.json
use screwdriver logger
https://github.com/screwdriver-cd/logger
=> fix: use screwdriver-logger

config/custom-environment-variables.yaml, config/default.yaml
=> fix: clarify timeout values

.gitignore, README.md, package.json
https://github.com/screwdriver-cd/screwdriver/issues/2285
=> fix: remove daviddm link [skip ci]

helpers/mime.js, plugins/builds.js
json is rendered as plain text. But this PR still doesn't seem to render it when tried locally. But we can atleast start sending the proper mime type for json
=> feat: try adding json to known mime types

bin/server, config/default.yaml
memory strategy was using incorrect package
use map to get correct package name
https://github.com/screwdriver-cd/screwdriver/issues/2358
=> fix(2358): memory strategy not using correct package

helpers/mime.js
=> fix: add xml and text to known mimes

helpers/aws.js, lib/server.js, package.json, plugins/auth.js, plugins/builds.js, plugins/caches.js, plugins/commands.js, plugins/logging.js, test/helpers/aws.test.js, test/lib/server.test.js, test/plugins/builds.test.js, test/plugins/caches.test.js, test/plugins/commands.test.js, test/plugins/stats.test.js, test/plugins/status.test.js, test/plugins/swagger.test.js
This PR updates eslint-config-screwdriver package to v5.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2492
=> feat(2492): Update to eslint-config-screwdriver v5

screwdriver.yaml
https://github.com/screwdriver-cd/screwdriver/issues/2514
=> fix: DIND for docker publish

screwdriver.yaml
=> fix: correct pipeline job order

Dockerfile.local, helpers/aws.js, package.json, plugins/builds.js, test/helpers/aws.test.js, test/plugins/builds.test.js
To implement SD_ZIP_ARTIFACTS feature by [new design](https://github.com/screwdriver-cd/screwdriver/blob/0962d20d251c0b7c03d40b7e4b10bb1ed009831d/design/sd-zip-artifacts.md)
Add an endpoint for deleting zip files.
- Added an endpoint for deleting zip files
- This endpoint is currently only used by unzip wokrers, so the scope is limited to unzip workers
- Update `Dockerfile.local` because the version of node is old and failed to build
- Removes old package.json section for noop plugin
[design doc](https://github.com/screwdriver-cd/screwdriver/blob/0962d20d251c0b7c03d40b7e4b10bb1ed009831d/design/sd-zip-artifacts.md#sd-api-api)
[issue](https://github.com/screwdriver-cd/screwdriver/issues/1500)
I confirm that this contribution is made under the terms of the license found in the root directory …
=> [1] fix(1500): Added the function to delete zip files

Dockerfile, Dockerfile.local, package.json, plugins/builds.js, plugins/caches.js, screwdriver.yaml, test/helpers/aws.test.js, test/lib/server.test.js, test/plugins/builds.test.js, test/plugins/caches.test.js, test/plugins/commands.test.js
https://github.com/screwdriver-cd/screwdriver/issues/2683
=> feat(2683): nodejs upgrade

plugins/builds.js, plugins/caches.js, plugins/commands.js
`config` throws error when you attempt to modify loaded config
use new object instead of changing loaded config
=> fix: fix config error

helpers/mime.js
Add more extension that are displayable
add `.toml` and `.editorconfig`
=> fix: add toml and editorconfig extensions

test/helpers/aws.test.js, test/plugins/commands.test.js
In addition to the following PR, modify the test regarding command upload
https://github.com/screwdriver-cd/store/pull/138
This PR is a test fix only.
This PR will remove unnecessary mock and fix test on command upload
related PR
https://github.com/screwdriver-cd/store/pull/138
=> fix: command upload test

Dockerfile, Dockerfile.local, package.json, screwdriver.yaml
BREAKING CHANGE: Node22
Update Node.js and dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/3282
=> feat(3282): upgrade Node.js v22 and dependencies. BREAKING CHANGE: Node22
